version: "3.8"
services:
  web:
    build: ./web-app
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
    - "3306:3306"